Update contributing info to ssh methods
sstsimulator/sst-macro pull request #595
Opened 2021-03-16 17:05 UTC by allevin

Updating the CONTRIBUTING.md file to reflect using ssh clones.  https clones authentication will be unsupported by Github in Aug 2021.

2021-03-16 18:42 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2021-03-16 18:44 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 4</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 11</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 4</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 11</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 3</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 10</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 38</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 3</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 10</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: MACRO (allevin/sst-macro)</dt>
  <ul>
    <li>Branch: update_contrib</li>
    <li>SHA: a941ced89ecf981dd16cf538bcddd5e4a8dc9f30</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: c3f5ac7ed4cc360e983b8ee009a30477972793ca</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 130ee4e31326c69e42d904ea43d573a2757ce66b</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 870f6ae65a9e6ca970aa2c18535b36f568d7c50c</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: allevin
</details>
</details>

2021-03-16 19:13 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 4</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 11</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 4</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 11</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 3</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 10</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 38</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 3</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 10</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2021-03-16 19:14 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2021-03-16 19:14 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-16 23:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-17 03:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-17 07:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-17 12:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-17 16:19 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-17 20:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-18 01:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-18 05:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-18 09:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-18 13:18 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-18 14:26 UTC, jjwilke requested changes
why are we switching to ssh here? That seems to be the only change.  People should be able to translate between ssh/https.

2021-03-18 14:47 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2021-03-18 14:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-18 19:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-18 23:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-19 03:20 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-19 07:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-19 12:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-19 17:31 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-19 21:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-20 02:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-20 06:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-20 11:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-20 15:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-20 19:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-21 00:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-21 04:20 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-21 08:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-21 12:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-21 17:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-21 21:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-22 01:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-22 06:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-22 10:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-22 15:34 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-22 19:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-22 23:33 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-23 04:06 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-23 08:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-23 12:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-23 13:44 UTC, allevin commented
@jjwilke Github is moving away from 

> why are we switching to ssh here? That seems to be the only change. People should be able to translate between ssh/https.

@jjwilke Github is moving away from supporting http authentication in Aug 2021 (https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/).  Users must have Tokens or SSH + 2 factor authentication to interact with Github.  If they have token, they can use https.  We can skip this PR if you want to leave it at https.

2021-03-23 13:50 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2021-03-23 13:52 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 25</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 37</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 25</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 37</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 24</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 31</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 64</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 24</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: MACRO (allevin/sst-macro)</dt>
  <ul>
    <li>Branch: update_contrib</li>
    <li>SHA: a941ced89ecf981dd16cf538bcddd5e4a8dc9f30</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: c3f5ac7ed4cc360e983b8ee009a30477972793ca</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0b193e375adb42716c9b2e62c1ec4b48f55e16af</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0f6628c63a825f23b1e5d600be58120892aae79e</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: allevin
</details>
</details>

2021-03-23 14:24 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 25</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 37</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 25</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 37</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 24</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 31</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 64</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 24</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2021-03-23 14:24 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-23 18:50 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-23 23:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-24 03:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-24 07:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-24 13:24 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-24 17:53 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-24 23:27 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-25 04:57 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-25 09:22 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-25 16:12 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-25 20:31 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-26 02:01 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-26 06:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-26 10:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-26 14:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-26 19:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-26 23:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-27 03:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-27 07:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-27 12:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-27 16:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-27 20:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-28 01:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-28 05:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-28 09:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-28 13:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-28 17:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-28 22:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-29 02:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-29 06:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-29 10:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-29 15:58 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-29 20:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-30 00:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-30 05:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-30 10:52 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-30 15:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-03-30 16:16 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2021-03-30 16:17 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 34</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 53</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 34</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 53</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 33</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 40</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 80</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 33</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 52</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: MACRO (allevin/sst-macro)</dt>
  <ul>
    <li>Branch: update_contrib</li>
    <li>SHA: a941ced89ecf981dd16cf538bcddd5e4a8dc9f30</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: c3f5ac7ed4cc360e983b8ee009a30477972793ca</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: fb4a2efdca3ac5ce0c9ecf2041286b638278ccd4</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0b5a43325eff010359b3b50e76756a0aef213f75</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: allevin
</details>
</details>

2021-03-30 16:48 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 34</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 53</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 34</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 53</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 33</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 40</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 80</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 33</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 52</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2021-03-30 16:49 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-30 22:40 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-31 04:05 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-31 08:22 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-31 13:57 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-31 19:26 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-03-31 23:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-01 03:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-01 07:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-01 12:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-01 16:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-01 20:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-02 00:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-02 05:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-02 09:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-02 13:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-02 18:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-02 22:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-03 03:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-03 07:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-03 12:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-03 16:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-03 20:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-04 01:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-04 05:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-04 10:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-04 14:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-04 18:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-04 22:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-05 03:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-05 07:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-05 11:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-05 15:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-05 18:01 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-05 22:40 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-06 02:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-06 07:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-06 11:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-06 15:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-06 19:27 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-06 23:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-07 04:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-07 08:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-07 12:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-07 17:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-07 21:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-08 02:36 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-08 06:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-08 11:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-08 15:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-08 19:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-09 02:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-09 07:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-09 11:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-09 16:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-09 20:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-10 00:18 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-10 04:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-10 08:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-10 13:17 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-10 17:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-10 21:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-11 02:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-11 06:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-11 11:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-11 15:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-11 20:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-12 00:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-12 04:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-12 08:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-12 12:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-12 17:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-12 21:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-04-12 21:50 UTC, nmhamster commented
Can someone approve this PR, its sitting in the testing cycle for ages!

2021-04-12 22:15 UTC, jpkenny approved these changes

2021-04-12 22:16 UTC, merged