Add support for MPI_PROC_NULL
sstsimulator/sst-macro pull request #599
Opened 2021-04-06 18:06 UTC by jjwilke

2021-04-06 19:27 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2021-04-06 19:29 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 60</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 60</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 35</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 42</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 87</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 35</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 59</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 12541bae2d704b45fc5a38056ca636e1de577a7f</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: c3f5ac7ed4cc360e983b8ee009a30477972793ca</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 9301425421592d8a322de176dd1423e85bfe0eb8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (jjwilke/sst-macro)</dt>
  <ul>
    <li>Branch: mpi-proc-null</li>
    <li>SHA: 010a50105750ad436d92739953aa3ef3fc089168</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jjwilke
</details>
</details>

2021-04-06 19:58 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 60</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 60</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 35</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 42</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 87</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 35</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 59</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2021-04-06 19:58 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2021-04-06 19:58 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-07 00:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-07 04:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-07 08:16 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-07 12:46 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-07 15:37 UTC, jpkenny requested changes
I don't think (but I could be wrong) that the status object that we return for receive with MPI_PROC_NULL as source satisfies: "When a receive with source = MPI_PROC_NULL is executed then the status object returns source = MPI_PROC_NULL, tag = MPI_ANY_TAG and count = 0."

2021-04-07 15:46 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2021-04-07 15:47 UTC, sst-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-04-07 16:01 UTC, jjwilke commented
> I don't think (but I could be wrong) that the status object that we return for receive with MPI_PROC_NULL as source satisfies: "When a receive with source = MPI_PROC_NULL is executed then the status object returns source = MPI_PROC_NULL, tag = MPI_ANY_TAG and count = 0."

That's a good catch. I will fix that.

2021-04-07 19:47 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2021-04-07 19:49 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 37</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 62</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 37</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 62</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 43</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 89</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 61</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 12541bae2d704b45fc5a38056ca636e1de577a7f</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: c3f5ac7ed4cc360e983b8ee009a30477972793ca</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 9301425421592d8a322de176dd1423e85bfe0eb8</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (jjwilke/sst-macro)</dt>
  <ul>
    <li>Branch: mpi-proc-null</li>
    <li>SHA: bac0101a59c1be2cf6e225601f53fff9c71c9c36</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: jjwilke
</details>
</details>

2021-04-07 20:08 UTC, jpkenny approved these changes
Approved.

2021-04-07 20:18 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 37</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-10.14-XC11_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 62</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 37</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 62</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 43</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 89</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 36</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 61</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2021-04-07 20:18 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ jpkenny ]!

2021-04-07 20:18 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

2021-04-07 21:47 UTC, merged