Remove std::thread.
sstsimulator/sst-macro pull request #683
Opened 2022-08-03 19:05 UTC by jmlapre

Add in pthreads in its place.

Erase this information and put your Pull Request comments here 
---

Instructions for Issuing a Pull Request to sst-macro
----------------------------------------------------

1 - Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-macro

2 - Verify that Source branch is up to date with the devel branch of sst-macro

3 - After submitting your Pull Request:
   * Automatic Testing will commence in a short while 
      * Pull Requests will be tested with the devel branches of the sst-core and sst-sqe repositories
         * These branches are syncronized with the devel branch of sst-macro.  This is why is it important to keep your source branch up to date.
      * If testing passes, the source branch will be automatically merged (if possible)
         * Pull Requests from forks will not be automatically tested until the code is inspected.
         * Pull Requests from forks will not be automatically merged into the devel branch.
      * If testing fails, You will be notified of the test results.  
         * The Pull Request will be retested on a regular basis - Changes to the source branch can be made to correct problems
         
----

2022-08-03 20:05 UTC, jpkenny requested changes
Looks good, just need to add the tls test back into tests/Makefile.check_programs

2022-08-03 20:55 UTC, jpkenny approved these changes
LGTM

2022-08-03 21:28 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-08-03 21:28 UTC, sst-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-08-03 21:34 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SST__AutotestGen2_NewFW_OSX-12.3-XC13_OMPI-4.0.5_PY3.9_sst-macro_nosstcore to start: Total Wait = 303
- Other jobs have been previously started - We must stop them...

2022-08-04 02:03 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SST__AutotestGen2_NewFW_OSX-12.3-XC13_OMPI-4.0.5_PY3.9_sst-macro_nosstcore to start: Total Wait = 303
- Other jobs have been previously started - We must stop them...

2022-08-04 06:34 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SST__AutotestGen2_NewFW_OSX-12.3-XC13_OMPI-4.0.5_PY3.9_sst-macro_nosstcore to start: Total Wait = 303
- Other jobs have been previously started - We must stop them...

2022-08-04 11:04 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job SST__AutotestGen2_NewFW_OSX-12.3-XC13_OMPI-4.0.5_PY3.9_sst-macro_nosstcore to start: Total Wait = 303
- Other jobs have been previously started - We must stop them...

2022-08-04 19:48 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-12.3-XC13_OMPI-4.0.5_PY3.9_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 1</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-12.3-XC13_OMPI-4.0.5_PY3.9_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 1</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 81</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 330</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 80</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 87</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 357</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 80</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 328</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: MACRO (jmlapre/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 1b9a6f3092b3945021c3a98100ee846d6ac65dd1</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: b6e8c5652bf9840e695a66fb3317290e1918f9de</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 19a6ad660b6d44dffc605f0981b33154ecbd7419</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: CORE (sstsimulator/sst-core)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: bcd759f8855943c2e253cbb0c60d1f41f0cb61b1</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: jmlapre
</details>
</details>

2022-08-04 20:08 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-12.3-XC13_OMPI-4.0.5_PY3.9_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 1</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_OSX-12.3-XC13_OMPI-4.0.5_PY3.9_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 1</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 81</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 330</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_Make-Dist</h3>
<ul>
  <li>Build Num: 80</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 87</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY3.8_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 357</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_nosstcore</h3>
<ul>
  <li>Build Num: 80</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 328</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

2022-08-04 20:08 UTC, sst-autotester commented
Status Flag 'Pre-Merge Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2022-08-04 20:08 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

2022-08-05 00:17 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

2022-08-05 04:17 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

2022-08-05 08:17 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

2022-08-05 12:47 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

2022-08-05 16:47 UTC, sst-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

2022-08-05 19:52 UTC, merged

2022-08-05 20:26 UTC, jmlapre commented
Closes #675